name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.203
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create nupkg
        run: dotnet pack --configuration Nuget --output .\nupkg\
      - name: Publish nupkg
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
        run: dotnet nuget push .\nupkg\*.pkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json